{
 "title": "Operations Overview",
 "tags": [
  "zabbix",
  "overview",
  "noc"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "site", "label": "Site", "query": { "query": "label_values(site)" } }
  ]
 },
 "panels": [
  {
   "title": "Device Availability  (Up / Down)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Firewall Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Firewall\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Firewall\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Firewall\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Firewall\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Firewall\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Firewall\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Firewall\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Firewall\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Switch Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Switch\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Switch\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Switch\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Switch\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Switch\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Switch\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Switch\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Switch\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Server Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Server\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Server\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Server\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Server\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Server\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Server\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Server\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Server\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Storage Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Storage\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Storage\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Storage\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Storage\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Storage\", site=~\"$site\"}) == 1) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Storage\", site=~\"$site\"}) == 1)) or vector(0)",
     "legendFormat": "Up"
    },
    {
     "expr": "count((max by(host) ({__name__=\"ICMP ping\", host_type=\"Storage\", site=~\"$site\"}) == 0) or (max by(host) ({__name__=\"Zabbix agent availability\", host_type=\"Storage\", site=~\"$site\"}) == 2)) or vector(0)",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Events Summary  (Active Problems by Severity)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  { "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 9 }, "options": { "content": "**Firewall Events**" } },
  {
   "title": "Firewall Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "group": { "filter": "/Firewall/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       5
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Firewall/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       4
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Firewall/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       3
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Firewall/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       2
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Firewall/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       1
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 6, "x": 6, "y": 9 }, "options": { "content": "**Switch Events**" } },
  {
   "title": "Switch Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "group": { "filter": "/Switches/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       5
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Switches/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       4
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Switches/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       3
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Switches/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       2
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Switches/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       1
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 9 }, "options": { "content": "**Server Events**" } },
  {
   "title": "Server Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "group": { "filter": "/Servers/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       5
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Servers/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       4
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Servers/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       3
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Servers/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       2
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/Servers/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       1
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 9 }, "options": { "content": "**Storage Events**" } },
  {
   "title": "Storage Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "group": { "filter": "/[Ss]torage/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       5
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/[Ss]torage/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       4
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/[Ss]torage/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       3
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/[Ss]torage/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       2
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    },
    {
     "group": { "filter": "/[Ss]torage/" },
     "host": { "filter": "" },
     "application": { "filter": "" },
     "item": { "filter": "" },
     "trigger": { "filter": "" },
     "options": {
      "severities": [
       1
      ],
      "minSeverity": 0,
      "acknowledged": 2,
      "hostsInMaintenance": false,
      "sortProblems": "default",
      "limit": 200,
      "useTimeRange": false
     }
    }
   ]
  }
 ]
}